// SPDX-License-Identifier: UNLICENSED
// !! THIS FILE WAS AUTOGENERATED BY abi-to-sol v0.8.0. SEE SOURCE BELOW. !!
pragma solidity >=0.7.0 <0.9.0;
pragma experimental ABIEncoderV2;

interface IImpermaxV2SolidlyRouter01 {
    function WETH() external view returns (address);

    function _optimalLiquidityUniV2(
        address uniswapV2Pair,
        uint256 amount0Desired,
        uint256 amount1Desired,
        uint256 amount0Min,
        uint256 amount1Min
    ) external view returns (uint256 amount0, uint256 amount1);

    function execute(
        address lp,
        bytes memory actionsData,
        bytes memory permitsData
    ) external payable;

    function factory() external view returns (address);

    function getBorrowable(address lp, uint8 index)
    external
    view
    returns (address borrowable);

    function getCollateral(address lp)
    external
    view
    returns (address collateral);

    function getLendingPool(address lp)
    external
    view
    returns (LendingPool memory pool);

    function impermaxBorrow(
        address sender,
        address borrower,
        uint256 borrowAmount,
        bytes memory data
    ) external;

    function impermaxRedeem(
        address sender,
        uint256 redeemAmount,
        bytes memory data
    ) external;

    struct LendingPool {
        address lp;
        address collateral;
        address[2] borrowables;
        address[2] tokens;
    }

    enum PermitType {
        PERMIT1,
        PERMIT_NFT,
        PERMIT2_SINGLE,
        PERMIT2_BATCH,
        PERMIT_BORROW
    }
    struct Permit {
        PermitType permitType;
        bytes permitData;
        bytes signature;
    }
    struct Permit1Data {
        address token;
        uint amount;
        uint deadline;
    }

    enum Type {
        BORROW,
        REPAY_USER,
        REPAY_ROUTER,
        WITHDRAW_TOKEN,
        WITHDRAW_ETH,
        NO_ACTION,
        MINT_UNIV2_EMPTY,
        MINT_UNIV2_INTERNAL,
        MINT_UNIV2,
        REDEEM_UNIV2,
        BORROW_AND_MINT_UNIV2,
        MINT_UNIV3_EMPTY,
        MINT_UNIV3_INTERNAL,
        MINT_UNIV3,
        REDEEM_UNIV3,
        BORROW_AND_MINT_UNIV3,
        MINT_AERO_EMPTY
    }
    struct Action {
        Type actionType;
        bytes actionData;
        bytes nextAction;
    }
    struct BorrowData {
        uint8 index;
        uint amount;
        address to;
    }

    struct MintUniV2Data {
        uint lpAmountUser;
        uint amount0Desired;
        uint amount1Desired;
        uint amount0Min;
        uint amount1Min;
    }
}

