name: Lint

on:
    push:
      branches:
        - main
    pull_request: { }
    workflow_dispatch: { }
  
env:
    FOUNDRY_PROFILE: ci

jobs:
    check:
        strategy:
            fail-fast: true

        name: Formatter
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                submodules: recursive
      
            - name: Install Foundry
              uses: foundry-rs/foundry-toolchain@v1
              with:
                version: nightly

            - name: Run forge fmt --check
              run: forge fmt --check
